# Generated by Django 3.2.13 on 2022-06-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('number', models.CharField(blank=True, max_length=12, verbose_name='Номер')),
                ('email', models.CharField(max_length=60, verbose_name='Электронная почта')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('type', models.CharField(max_length=14, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60, verbose_name='Название проекта')),
                ('customer', models.CharField(max_length=40, verbose_name='Заказчик')),
                ('time_completion', models.CharField(max_length=40, verbose_name='Время завершения')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='PriceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=60, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=40, verbose_name='Цена')),
                ('time_completion', models.CharField(max_length=40, verbose_name='Время исполнения')),
            ],
            options={
                'verbose_name': 'Цена услуг',
                'verbose_name_plural': 'Цены услуг',
            },
        ),
    ]
